### ISSUE TITLE
Where is the code of conduct?

### ISSUE THREAD

**Issue by alfaproject** [intellix/is-billy-scottish#5]
As title says.

**Comment by alfaproject** [comment]
Calling interested parties for feedback @intellix @aalstes @billymcintosh @panickz @tobybowers

**Comment by aalstes** [comment]
![image](https://user-images.githubusercontent.com/5175628/59977808-189d1b00-95d6-11e9-8bc9-7c26b0350a91.png)

**Comment by aalstes** [comment]
pls unmerge asap

**Comment by intellix** [comment]
Implemented!
